base_relics = [
    "Aegis Amulet",
    "Belt of Frenzy",
    "Blink Rune",
    "Bracer of Radiance",
    "Cloak of Meditation",
    "Cursed Ankh",
    "Heavenly Wings",
    "Horrific Emblem",
    "Magic Shell",
    "Purification Beads",
    "Shield of Thorns",
    "Sundering Spear",
    "Teleport Fragment",
]

consumables = [
    "Chalice of Healing",
    "Chalice of Mana",
    "Chalice of the Oracle",
    "Elixir of Defense",
    "Elixir of Power",
    "Healing Potion",
    "Mana Potion",
    "Multi Potion",
    "Potion of Power",
    "Runic Bomb",
    "Sentry Ward",
    "Scare Tactics",
    "Ward",
]

god_items = ["Baron's Brew"]

greater_relics = [
    "Greater Aegis Amulet",
    "Greater Belt of Frenzy",
    "Greater Blink Rune",
    "Greater Bracer of Radiance",
    "Greater Cloak of Meditation",
    "Greater Cursed Ankh",
    "Greater Heavenly Wings",
    "Greater Horrific Emblem",
    "Greater Magic Shell",
    "Greater Purification Beads",
    "Greater Shield of Thorns",
    "Greater Sundering Spear",
    "Greater Teleport Fragment",
]

relics = [
    "Aegis of Acceleration",
    "Aegis of Judgement",
    "Belt of Insatiable Hunger",
    "Belt of the Berserker",
    "Blighted Ankh",
    "Bracer of Brilliance",
    "Bracer of Illumination",
    "Chaotic Beads",
    "Cloak of the Ascetic",
    "Cloak of the Avatar",
    "Corrupted Blink Rune",
    "Drowned Ankh",
    "Emblem of Increasing Peril",
    "Emblem of Trembling Terror",
    "Entangling Wings",
    "Fortifying Shell",
    "Hastened Wings",
    "Heroic Teleport",
    "Persistent Teleport",
    "Phantom Shell",
    "Scorching Blink Rune",
    "Sundering Blast",
    "Sundering Siphon",
    "Temporal Beads",
    "Thorns of Overgrowth",
    "Thorns of Sapping Strength",
]

shards = ["Carapace Shard", "Vision Shard", "Horn Shard", "Claw Shard", "Wing Shard"]

starter_items = [
    "Animosity",
    "Archmage's Gem",
    "Axe of Animosity",
    "Benevolence",
    "Blood-soaked Shroud",
    "Bluestone Brooch",
    "Bluestone Pendant",
    "Bumba's Dagger",
    "Bumba's Hammer",
    "Bumba's Spear",
    "Compassion",
    "Conduit Gem",
    "Corrupted Bluestone",
    "Death's Embrace",
    "Death's Temper",
    "Death's Toll",
    "Diamond Arrow",
    "Eye of the Jungle",
    "Gem of Focus",
    "Gilded Arrow",
    "Heroism",
    "Hunter's Cowl",
    "Infused Sigil",
    "Leader's Cowl",
    "Leather Cowl",
    "Manikin Hidden Blade",
    "Manikin Mace",
    "Manikin Scepter",
    "Ornate Arrow",
    "Pendulum of Ages",
    "Protector of the Jungle",
    "Sacrificial Shroud",
    "Sands of Time",
    "Seer of the Jungle",
    "Sentinel's Boon",
    "Sentinel's Embrace",
    "Sentinel's Gift",
    "Sigil of The Old Guard",
    "Spartan Flag",
    "Sundering Axe",
    "Tainted Amulet",
    "Tainted Breastplate",
    "Tainted Steel",
    "The Alternate Timeline",
    "Vampiric Shroud",
    "War Banner",
    "War Flag",
    "Warding Sigil",
    "Warrior's Axe",
]
