
patch = "8.12"
godsDict = {
    "Achilles": 0,
    "Agni": 0,
    "Ah Muzen Cab": 0,
    "Ah Puch": 0,
    "Amaterasu": 0,
    "Anhur": 0,
    "Anubis": 0,
    "Ao Kuang": 0,
    "Aphrodite": 0,
    "Apollo": 0,
    "Arachne": 0,
    "Ares": 0,
    "Artemis": 0,
    "Artio": 0,
    "Athena": 0,
    "Atlas": 0,
    "Awilix": 0,
    "Baba Yaga": 0,
    "Bacchus": 0,
    "Bakasura": 0,
    "Baron Samedi": 0,
    "Bastet": 0,
    "Bellona": 0,
    "Cabrakan": 0,
    "Camazotz": 0,
    "Cerberus": 0,
    "Cernunnos": 0,
    "Chaac": 0,
    "Chang\'e": 0,
    "Charybdis": 0,
    "Chernobog": 0,
    "Chiron": 0,
    "Chronos": 0,
    "Cliodhna": 0,
    "Cthulhu": 0,
    "Cu Chulainn": 0,
    "Cupid": 0,
    "Da Ji": 0,
    "Danzaburou": 0,
    "Discordia": 0,
    "Erlang Shen": 0,
    "Eset": 0,
    "Fafnir": 0,
    "Fenrir": 0,
    "Freya": 0,
    "Ganesha": 0,
    "Geb": 0,
    "Gilgamesh": 0,
    "Guan Yu": 0,
    "Hachiman": 0,
    "Hades": 0,
    "He Bo": 0,
    "Heimdallr": 0,
    "Hel": 0,
    "Hera": 0,
    "Hercules": 0,
    "Horus": 0,
    "Hou Yi": 0,
    "Hun Batz": 0,
    "Izanami": 0,
    "Janus": 0,
    "Jing Wei": 0,
    "Jormungandr": 0,
    "Kali": 0,
    "Khepri": 0,
    "King Arthur": 0,
    "Kukulkan": 0,
    "Kumbhakarna": 0,
    "Kuzenbo": 0,
    "Loki": 0,
    "Medusa": 0,
    "Mercury": 0,
    "Merlin": 0,
    "Morgan Le Fay": 0,
    "Mulan": 0,
    "Ne Zha": 0,
    "Neith": 0,
    "Nemesis": 0,
    "Nike": 0,
    "Nox": 0,
    "Nu Wa": 0,
    "Odin": 0,
    "Olorun": 0,
    "Osiris": 0,
    "Pele": 0,
    "Persephone": 0,
    "Poseidon": 0,
    "Ra": 0,
    "Raijin": 0,
    "Rama": 0,
    "Ratatoskr": 0,
    "Ravana": 0,
    "Scylla": 0,
    "Serqet": 0,
    "Set": 0,
    "Skadi": 0,
    "Sobek": 0,
    "Sol": 0,
    "Sun Wukong": 0,
    "Susano": 0,
    "Sylvanus": 0,
    "Terra": 0,
    "Thanatos": 0,
    "The Morrigan": 0,
    "Thor": 0,
    "Thoth": 0,
    "Tiamat": 0,
    "Tsukuyomi": 0,
    "Tyr": 0,
    "Ullr": 0,
    "Vamana": 0,
    "Vulcan": 0,
    "Xbalanque": 0,
    "Xing Tian": 0,
    "Yemoja": 0,
    "Ymir": 0,
    "Zeus": 0,
    "Zhong Kui": 0
}


Assassins = ["Arachne", "Awilix", "Bakasura", "Bastet", "Camazotz", "Da Ji", "Fenrir", "Hun Batz", "Kali", "Loki", "Mercury", "Ne Zha", "Nemesis", "Pele", "Ratatoskr", "Ravana", "Serqet", "Set", "Susano", "Thanatos", "Thor", "Tsukuyomi"]
Guardians = ["Ares", "Artio", "Athena", "Atlas", "Bacchus", "Cabrakan", "Cerberus",  "Fafnir", "Ganesha", "Geb", "Jormungandr", "Khepri", "Kumbhakarna", "Kuzenbo", "Sobek", "Sylvanus", "Terra", "Xing Tian", "Yemoja", "Ymir"]
Hunters = ["Ah Muzen Cab", "Anhur", "Apollo", "Artemis", "Cernunnos", "Charybdis","Chernobog", "Chiron", "Cupid", "Danzaburou", "Hachiman", "Heimdallr", "Hou Yi", "Izanami", "Jing Wei", "Medusa", "Neith", "Rama", "Skadi", "Ullr", "Xbalanque"]
Mages = ["Agni", "Ah Puch", "Anubis", "Ao Kuang", "Aphrodite", "Baba Yaga", "Baron Samedi", "Chang\'e", "Chronos", "Discordia", "Eset", "Freya", "Hades", "He Bo", "Hel", "Hera", "Janus", "Kukulkan", "Merlin", "Morgan Le Fay",
         "Nox", "Nu Wa", "Olorun", "Persephone", "Poseidon", "Ra", "Raijin", "Scylla", "Sol", "The Morrigan", "Thoth", "Tiamat", "Vulcan", "Zeus", "Zhong Kui"]
Warriors = ["Amaterasu", "Achilles", "Bellona", "Chaac", "Cu Chulainn", "Erlang Shen", "Gilgamesh", "Guan Yu", "Hercules", "Horus", "King Arthur", "Mulan", "Nike", "Odin", "Osiris", "Sun Wukong", "Tyr", "Vamana"]


roles = ["Carry", "Support", "Mid", "Jungle", "Solo"]
ranks = ["Bronze", "Silver", "Gold", "Platinum", "Diamond", "Masters", "Grandmaster"]
# ranks = ["Bronze", "Silver", "Gold", "Platinum", "Diamond", "Masters", "Grandmaster", "All Ranks"]
slots = ["slot1", "slot2", "slot3", "slot4", "slot5", "slot6"]

single_combat_stats = ["kills", "deaths", "assists", "damage_player", "damage_taken", "damage_mitigated", "healing", "healing_self"]
single_objective_stats = ["gold", "damage_bot", "kills_bot", "camps_cleared", "tower_kills", "phoenix_kills", "tower_damage", "objective_assists", "wards_placed"]

Tier_Three_items = [
"Ninja Tabi", "Shoes of Focus", "Relic Dagger", "Shield of Regrowth", "Lotus Crown", "Heartward Amulet",
"Sovereignty", "Jade Emperor\'s Crown", "Atalanta\'s Bow", "Shogun\'s Kusari", "Ancile", "Breastplate of Valor", "Divine Ruin",
"Poisoned Star", "The Sledge", "Mystical Mail", "Charon\'s Coin", "Runeforged Hammer", "Ichaival", "Dominance", "Spirit Robe",
"Obsidian Shard", "Berserker\'s Shield", "Rod Asclepius", "Void Shield", "Chronos\' Pendant", "Telkhines Ring", "Typhon\'s Fang",
"Deathbringer", "Reinforced Greaves", "Talaria Boots", "Winged Blade", "Bristlebush Acorn", "Thickbark Acorn", "Odysseus\' Bow",
"Spectral Armor", "Magi\'s Cloak", "Blackthorn Hammer", "Silverbranch Bow", "Pestilence", "Bulwark of Hope", "Frostbound Hammer",
"Polynomicon", "Brawler\'s Beat Stick", "Shifter\'s Shield", "Gladiator\'s Shield", "Shadowsteel Shuriken", "Bancroft\'s Talon",
"Hastened Katana", "Warlock\'s Staff", "Spear of the Magus", "Book of the Dead", "Spear of Desolation", "Malice", "Gem of Isolation",
"Bloodforge", "Doom Orb", "Rod of Tahuti", "Reinforced Shoes", "Traveler\'s Shoes", "Emperor\'s Armor", "Contagion", "Thistlethorn Acorn",
"Oni Hunter\'s Garb", "Celestial Legion Helm", "Runic Shield", "Genji\'s Guard", "The Executioner", "Stone of Gaia", "Demonic Grip",
"Lono\'s Mask", "Pythagorem\'s Piece", "Guanlet of Thebes", "Stone Cutting Sword", "Mail of Renewal", "The Crusher", "Book of Thoth",
"Rage", "Wind Demon", "Titan\'s Bane", "Ethereal Staff", "Transcendence", "Serrated Edge", "Hastened Ring", "Fail-not", "Heartseeker",
"Shoes of the Magi", "Warrior Tabi", "Golden Blade", "Evergreen Acorn", "Witchblade", "Soul Eater", "Hydra\'s Lament", "Talisman of Energy",
"Hide of the Nemean Lion", "Toxic Blade", "Void Stone", "Devourer\'s Gauntlet", "Midgardian Mail", "Soul Gem", "Jotunn\'s Wrath", "Stone of Fal",
"Pridwen", "Hide of the Urchin", "Caduceus Shield", "Rangda\'s Mask", "Asi", "Arondight", "Ring of Hecate", "Tyrannical Plate Helm", "Soul Reaver",
"Qin\'s Sais", "Staff of Myrddin", "Mantle of Discord", "Evolved Gauntlet of Thebes", "Evolved Transcendence", "Evolved Devourer\'s Gauntlet",
"Evolved Book of Thoth", "Evolved Charon\'s Coin", "Evolved Hide of the Urchin", "Evolved Rage", "Evolved Soul Eater", "Evolved Warlock\'s Staff"
]

Starter_items = [
"Animosity", "Archmage\'s Gem", "Benevolence", "Blood-soaked Shroud", "Bluestone Brooch", "Bluestone Pendant", "Bumba\'s Dagger",
"Bumba\'s Hammer", "Bumba\'s Spear", "Compassion", "Conduit Gem", "Corrupted Bluestone", "Death\'s Embrace", "Death\'s Temper", 
"Death\'s Toll", "Diamond Arrow", "Eye of the Jungle", "Gem of Focus", "Gilded Arrow", "Hero\'s Axe", "Hunter\'s Cowl", "Infused Sigil",
"Leader\'s Cowl", "Leather Cowl", "Manikin Hidden Blade", "Manikin Mace", "Manikin Scepter", "Ornate Arrow", "Pendulum of Ages",
"Protector of the Jungle", "Sacrifical Shroud", "Sands of Time", "Seer of the Jungle", "Sentinel\'s Boon", "Sentinel\'s Embrace",
"Sentinel\'s Gift", "Sigil of the Old Guard", "Spartan Flag", "Sundering Axe", "Tainted Amulet", "Tainted Breastplate", "Tainted Steel",
"The Alternate Timeline", "Vampiric Shroud", "War Banner", "War Flag", "Warding Sigil", "Warrior\'s Axe"
]


num_hits_dict = {
    "Achilles": {
        "Shield of Achilles": 1,
        "Radiant Glory": 0,
        "Combat Dodge": 2,
        "Fatal Strike": 1,
        "Gift of the Gods": 0,
    },
    "Agni": {
        "Noxious Fumes Damage per Tick": 10,
        "Noxious Fumes Explosion Damage": 1,
        "Flame Wave": 1,
        "Path of Flames Damage per Tick": 4,
        "Rain Fire": 3,
        "Combustion": 1,
        "Combustion Damage per Tick": 6
    },
    "Ah Puch": {
        "Undead Surge": 2,
        "Corpse Explosion Initial Damage": 1,
        "Corpse Explosion Damage per Corpse": 3,
        "Fleeting Breath Damage per Tick": 4,
        "Fleeting Breath Additional Damage": 1,
        "Empty the Crypts": 132,
        "Hollow Ground": 0,
    },  
    "Amaterasu": {
        "Divine Presence": 0,
        "Heavenly Reflection Full Charge": 1,
        "Glorious Charge": 1,
        "Dazzling Offensive": 3,
        "Illuminating Strike": 0,
    },
    "Anubis": {
        "Plague of Locusts": 6,
        "Mummify": 1,
        "Grasping Hands": 4,
        "Death Gaze": 30,
        "Sorrow": 0
    },
    "Ao Kuang": {
        "Water Illusion": 1,
        "Dragon Call Attack Damage": 6,
        "Wild Storm": 1,
        "King of the Eastern Seas Damage": 1,
        "King of the Eastern Seas Landing Damage": 1,
        "Dragon King's Sword": 0,
    },
    "Aphrodite": {
        "Kiss": 0,
        "Back Off!": 1,
        "Love Birds": 6,
        "Undying Love": 0,
        "Center of Attention": 0,
    },
    "Arachne": {
        "Venomous Bite Initial Damage": 1,
        "Venomous Bite Damage per Tick": 6,
        "Cocoon": 0,
        "Web Broodling": 60, # = num broodling * seconds * attacks per seconds (6 * 10 * 1)
        "Night Crawler": 1,
    },
    "Awilix": {
        "Summon Suku": 1,
        "Feather Step": 2,
        "Moonlight Charge": 1,
        "Gravity Surge": 1,
        "Initiative": 0,
    },
    "Baba Yaga": {
        "Wild Witchcraft": 1,
        "Baba's Brew": 2,
        "Blast Off!": 1,
        "Home Sweet Home Landing Damage:": 1,
        "Home Sweet Home Burst Damage:": 4,
        "Home Sweet Home Burn Damage:": 20, # num burns * num bolts ( 3 * 4 )
    },
    "Bakasura": {
        "Take Down": 1,
        "Eat Minion": 0,
        "Butcher Blades": 0,
        "Regurgitate": 72, # = num minions * seconds * attacks per seconds (6 * 8 * 1)
        "Insatiable Hunger": 0,
    },
    "Baron Samedi": {
        "Vivid Gaze": 1,
        "Consign Spirits": 1,
        "Wrap It Up": 5,
        "Life of the Party Damage Per Tick:": 10,
        "Life of the Party Damage On Hit": 1,
        "Hysteria": 0,
    },
    "Bastet": {
        "Pounce": 1,
        "Razor Whip": 4,
        "Ensnaring Claw Root Damage": 1,
        "Ensnaring Claw Cat Damage": 4,
        "Huntress of Bast Initial Hit": 1,
        "Huntress of Bast Quicksand Damage": 6,
        "Nightstalker": 0,
    },
    "Bellona": {
        "Shield Bash": 1,
        "Bludgeon": 1,
        "Scourge": 1,
        "Eagle's Rally": 1,
        "Master of War": 0,
    },
    "Camazotz": {
        "Screech": 1,
        "Vampire Bats": 1,
        "Devour": 1,
        "Bat Out of Hell": 3,
        "Essence Drinker": 0
    },
    "Chaac": {
        "Thunder Strike": 1,
        "Torrent": 1,
        "Rain Dance": 0,
        "Storm Call": 1,
        "Overflow": 0,
    },
    "Chang'e": {
        "Crescent Moon Dance": 1,
        "Moonlit Waltz": 1,
        "Moonflower Dance": 1,
        "Waxing Moon": 1,
        "Jade Rabbit": 0,
    },
    "Chronos": {
        "Time Rift": 1,
        "Accelerate": 0,
        "Stop Time": 2,
        "Rewind": 0,
        "Time Lord": 1,
    },
    "Cliodhna": {
        "Banshee's Wail Scream Damage": 3,
        "Banshee's Wail Final Hit Damage": 1,
        "Flickering Visions": 1,
        "Lurching Claw Dash Damage": 1,
        "Lurching Claw Claw Damage": 1,
        "Tearing The Veil Opening Damage": 3,
        "Tearing The Veil Rift Damage": 20,
        "Phantasmal": 0,
    },
    "Cu Chulainn": {
        "Barbed Spear (Ground Slam)": 2,
        "Vent Anger": 12,
        "Salmon's Leap (Furious Charge)": 2,
        "Spear of Mortal Pain (War Cry)": 2,
        "Berserk": 0,
    },
    "Da Ji": {
        "Horrible Burns Burst Damage": 1,
        "Horrible Burns Damage Per Tick": 3,
        "One Thousand Cuts": 4,
        "Trickster Spirit": 1,
        "Paolao Shot Damage": 3,
        "Paolao Pull Damage per Tick": 3,
        "Torture Blades": 0,
    },
    "Discordia": {
        "Contest of Gods": 0,
        "Unruly Magic Orb Damage": 1,
        "Unruly Magic Minor Damage": 6,
        "Strife": 1,
        "Erratic Behavior": 0,
        "Golden Apple of Discord": 1,
    },   
    "Erlang Shen": {
        "Spot Weakness": 0,
        "Pin": 1,
        "72 Transformations": 1,
        "9 Turns Blessing": 0,
        "Howling Celestial Dog": 0,
    },
    "Eset": {
        "Wing Gust": 4,
        "Spirit Ball": 1,
        "Dispel Magic": 0,
        "Circle of Protection Damage:": 1,
        "Funeral Rites": 1,
    },
    "Fenrir": {
        "Unchained": 1,
        "Seething Howl": 0,
        "Brutalize": 4,
        "Ragnarok": 1,
        "Unbound Runes": 0,
    },
    "Freya": {
        "Irradiate": 0,
        "Pulse": 0,
        "Banish": 0,
        "Valkyrie's Discretion": 4,
        "Brisingamen's Blessing": 0,
    },
    "Gilgamesh": {
        "Sun-Forged Scimitar": 0,
        "Drop Kick": 1,
        "Hero's Advance": 1,
        "Winds of Shamash": 1,
        "Winds of Shamash Wind Damage": 11,
        "Winds of Shamash Binding Damage": 1,
        "Epic of Gilgamesh": 0
    },
    "Guan Yu": {
        "Conviction": 0,
        "Warrior's Will": 1,
        "Taolu Assault": 10,
        "Cavalry Charge": 6,
    },
    "Hades": {
        "Death From Below": 1,
        "Shroud of Darkness": 0,
        "Devour Souls Damage:": 1,
        "Devour Souls Detonated Damage:": 3,
        "Pillar of Agony": 8,
        "Blight": 0,
    },
    "He Bo": {
        "Water Cannon": 1,
        "Atlas of the Yellow River": 0,
        "Waterspout": 1,
        "Crushing Wave": 1,
        "Steady Flow": 0,
    },
    "Hel": {
        "Decay (Restoration)": 1,
        "Hinder (Cleanse)": 0,
        "Repulse (Inspire)": 1,
        "Switch Stances": 0,
        "Stance Attunement": 0,
    },
    "Hera": {
        "Royal Assault Cone Damage:": 1,
        "Royal Assault Fist Damage:": 2,
        "Polymorph": 1,
        "Divine Shroud": 10,
        "Argus, the Defender": 1,
        "Commanding Presence": 0,
    },
    "Hercules": {
        "Driving Strike": 1,
        "Earthbreaker": 1,
        "Mitigate Wounds": 0,
        "Excavate": 3,
        "Strength from Pain": 0,
    },
    "Horus": {
        "Updraft": 1,
        "Fracture": 1,
        "Protector's Surge": 0,
        "To The Skies!": 1,
        "Resolute": 0
    },
    "Hun Batz": {
        "Somersault": 1,
        "Overhand Smash": 1,
        "Sacred Monkey": 1,
        "Fear No Evil": 1,
        "Infused Strikes": 1
    },
    "Janus": {
        "Portal": 1,
        "Unstable Vortex": 2,
        "Threshold": 0,
        "Through Space and Time": 1,
        "Passages": 0,
    },
    "Kali": {
        "Nimble Strike": 1,
        "Lash Damage Per Blade": 3,
        "Lash Bleed Damage": 6, # bleed dmg ticks * blades ( 6 * 3 )
        "Incense": 0,
        "Destruction Damage": 1,
        "Marked for Death": 0,  
    },
    "King Arthur": {
        "Overhead Slash (Hamstring)": 1,
        "Battle Stomp (Uppercut)": 1,
        "Twin Cleave (Bladestorm)": 1,
        "Sundering Strike (Excalibur's Wrath)": 1,
        "Steadfast": 0,
    },
    "Kukulkan": {
        "Zephyr": 1,
        "Slipstream": 0,
        "Whirlwind": 12,
        "Spirit Of The Nine Winds": 1,
        "Power Of The Wind Jewel": 0,
    },
    "Loki": {
        "Vanish Damage per Tick": 4,
        "Agonizing Visions": 8,
        "Flurry Strike": 5,
        "Flurry Strike Final Damage": 1,
        "Assassinate Cripple Damage": 1,
        "Assassinate Heavy Damage": 1,
    },
    "Mercury": {
        "Made You Look": 1,
        "Maximum Velocity": 0,
        "Special Delivery": 4,
        "Sonic Boom": 1,
        "Fastest God Alive": 0,
    },
    "Mulan": {
        "Cross Strike": 3,
        "Spear Thrust": 2,
        "Grapple": 1,
        "Divine Mastery": 1,
        "Training Arc": 0,
    },
    "Ne Zha": {
        "Universe Ring Toss Initial Damage:": 1,
        "Universe Ring Toss Damage:": 4,
        "Flaming Spear": 0,
        "Armillary Sash": 1,
        "Wind Fire Wheels Damage per Hit": 6,
        "Wind Fire Wheels Damage (Initial/Landing)": 2,
        "Righteous Spirit": 0
    },
    "Nemesis": {
        "Swift Vengeance": 2,
        "Slice and Dice": 2,
        "Retribution": 0,
        "Divine Judgement": 0,
        "Scales of Fate": 0,
    },
    "Nike": {
        "Rend": 3,
        "Barrier Formation Damage": 1,
        "Barrier Formation Repel Damage": 8,
        "Valiant Leap": 1,
        "Sentinel of Zeus": 1,
    },
    "Odin": {
        "Lunge": 1,
        "Raven Shout": 1,
        "Gungnir's Might": 1,
        "Bird Bomb": 1,
        "Ring of Spears": 1,
        "Path to Valhalla": 0,
    },
    "Osiris": {
        "Sickle Strike": 1,
        "Spirit Flail": 1,
        "Judgement Tether": 0,
        "Lord of the Afterlife": 1,
        "Fragmented": 0,
    },
    "Pele": {
        "Pyroclast Damage:": 2,
        "Pyroclast Return Damage:": 10, # num return * pyroclast stacks ( 5 * 2 )
        "Eruption Inner Damage:": 1,
        "Eruption Outer Damage:": 1,
        "Magma Rush Damage:": 20,
        "Magma Rush Amplified Damage:": 10,
        "Volcanic Lightning Damage:": 1,
        "Volcanic Lightning Cone Damage:": 3,
        "Everlasting Flame": 1,
    },
    "Ratatoskr": {
        "Dart": 1,
        "Flurry": 4,
        "Acorn Blast": 3,
        "Through the Cosmos": 1,
        "Acorn of Yggdrasil": 0,
    },
    "Ravana": {
        "Prana Onslaught": 1,
        "Overhead Kick": 1,
        "10-Hand Shadow Fist": 1,
        "Mystic Rush Damage:": 1,
        "Chain of Blows": 0,
    },
    "Serqet": {
        "Deathbane": 3,
        "Catalyst": 0,
        "Cobra's Kiss": 2,
        "Ambush": 1,
        "Last Breath Damage": 1,
        "Last Breath Poison Damage": 5,
    },
    "Set": {
        "Skewer": 1,
        "Spawn of Set Dash Damage:": 8,
    },
    "Sun Wukong": {
        "The Magic Cudgel": 1,
        "Master's Will": 1,
        "72 Transformations": 1,
        "Somersault Cloud": 1,
        "Undefeated Body": 0
    },
    "Susano": {
        "Storm Kata": 3,
        "Wind Siphon": 1,
        "Jet Stream": 4,
        "Typhoon": 1,
        "Gathering Storm": 0
    },
    "Thanatos": {
        "Death Scythe Damage": 1,
        "Death Scythe Bonus Damage": 0,
        "Scent of Death": 0,
        "Soul Reap": 1,
        "Hovering Death": 1,
        "Harvester of Souls": 0,
    },
    "Thor": {
        "Mjolnir's Attunement": 2,
        "Tectonic Rift": 0,
        "Berserker Barrage Damage per Tick": 3,
        "Berserker Barrage Final swing Damage": 1,
        "Anvil of Dawn Damage": 1,
        "Anvil of Dawn Arc Damage": 3,
    },
    "Tsukuyomi": {
        "Dark Moon Shuriken": 1,
        "Kusarigama Swing Damage": 2,
        "Kusarigama Final Damage": 1,
        "Silver Moon Caltrops": 10,
        "Piercing Moonlight Beam Damage": 4,
        "Piercing Moonlight Dash Damage": 4,
        "Shingetsu & Mangetsu": 0
    },
    "Tyr": {
        "Fearless": 1,
        "Power Cleave": 2,
        "Change Stance": 0,
        "Lawbringer": 1,
        "Unyielding": 0,
    },
    "Vamana": {
        "Clear the Path": 1,
        "Armored Umbrella": 1,
        "Umbrellarang": 2,
        "Colossal Fury": 0,
        "Sleeping Giant": 0
    }
}

scaling_dict = {
    "Dazzling Offensive": {
        f"hit{i+1}": 20*i for i in range(3)
        },
    "Tearing The Veil Rift Damage": {
        **{"hit1": -40,},
        **{f"hit{i+2}": -80 for i in range (23)}
        },
    "Cavalry Charge": {       
            f"hit{i+1}": 20*i for i in range(6)
        },
    "Excavate": {
            "hit1": 0,
            "hit2": -50,
            "hit3": -50,
        },
    "Universe Ring Toss Damage:": {
        f"hit{i+1}": -65 for i in range(5)
    },
    "Mjolnir's Attunement": {
        "hit1": 0,
        "hit2": 100
    },
    "Vivid Gaze": {
        "hit1": 15,
    },
    "Spirit Ball": {
        "hit1": 50,
    },
    "Circle of Protection Damage:": {
        "hit1": 250,
    },
    "Royal Assault Fist Damage:": {
        "hit1": 15,
        "hit2": 15
    },
    "Unstable Vortex": {
        "hit1": 0,
        "hit2": -100 + 15
    },
}
