export const physicalItems = [
  { 'id': "Atalanta's Bow" }, { 'id': 'Ancile' }, { 'id': 'The Sledge' }, { 'id': 'Runeforged Hammer' }, { 'id': 'Ichaival' }, { 'id': 'Dominance' }, { 'id': "Berserker's Shield" }, { 'id': 'Void Shield' }, { 'id': 'Deathbringer' }, { 'id': 'Talaria Boots' }, { 'id': 'Bristlebush Acorn' }, { 'id': 'Thickbark Acorn' }, { 'id': 'Blackthorn Hammer' }, { 'id': 'Silverbranch Bow' }, { 'id': 'Frostbound Hammer' }, { 'id': "Brawler's Beat Stick" }, { 'id': "Shifter's Shield" }, { 'id': "Gladiator's Shield" }, { 'id': 'Shadowsteel Shuriken' }, { 'id': 'Hastened Katana' }, { 'id': 'Malice' }, { 'id': 'Bloodforge' }, { 'id': 'Thistlethorn Acorn' }, { 'id': 'Runic Shield' }, { 'id': 'The Executioner' }, { 'id': 'Stone Cutting Sword' }, { 'id': 'The Crusher' }, { 'id': 'Rage' }, { 'id': 'Wind Demon' }, { 'id': "Titan's Bane" }, { 'id': 'Transcendence' }, { 'id': 'Serrated Edge' }, { 'id': 'Fail-not' }, { 'id': 'Heartseeker' }, { 'id': 'Warrior Tabi' }, { 'id': 'Golden Blade' }, { 'id': 'Evergreen Acorn' }, { 'id': 'Soul Eater' }, { 'id': "Hydra's Lament" }, { 'id': "Devourer's Gauntlet" }, { 'id': "Jotunn's Wrath" }, { 'id': 'Caduceus Shield' }, { 'id': "Rangda's Mask" }, { 'id': 'Asi' }, { 'id': 'Arondight' }, { 'id': "Qin's Sais" }, { 'id': 'Evolved Transcendence' }, { 'id': "Evolved Devourer's Gauntlet" }, { 'id': 'Evolved Rage' }, { 'id': 'Evolved Soul Eater' }
]

export const magicalItems = [
  {'id': 'Lotus Crown'}, {'id': "Jade Emperor's Crown"}, {'id': 'Divine Ruin'}, {'id': "Charon's Coin"}, {'id': 'Obsidian Shard'}, {'id': "Chronos' Pendant"}, {'id': 'Telkhines Ring'}, {'id': "Typhon's Fang"}, {'id': 'Polynomicon'}, {'id': "Bancroft's Talon"}, {'id': "Warlock's Staff"}, {'id': 'Spear of the Magus'}, {'id': 'Book of the Dead'}, {'id': 'Spear of Desolation'}, {'id': 'Gem of Isolation'}, {'id': 'Doom Orb'}, {'id': 'Rod of Tahuti'}, {'id': "Traveler's Shoes"}, {'id': 'Celestial Legion Helm'}, {'id': 'Demonic Grip'}, {'id': "Pythagorem's Piece"}, {'id': 'Book of Thoth'}, {'id': 'Ethereal Staff'}, {'id': 'Hastened Ring'}, {'id': 'Void Stone'}, {'id': 'Soul Gem'}, {'id': 'Stone of Fal'}, {'id': "Rangda's Mask"}, {'id': 'Ring of Hecate'}, {'id': 'Tyrannical Plate Helm'}, {'id': 'Soul Reaver'}, {'id': 'Staff of Myrddin'}, {'id': 'Evolved Book of Thoth'}, {'id': "Evolved Charon's Coin"}, {'id': "Evolved Warlock's Staff"}
];

export const items = [ { 'id': "Atalanta's Bow" }, { 'id': 'Ancile' }, { 'id': 'The Sledge' }, { 'id': 'Runeforged Hammer' }, { 'id': 'Ichaival' }, { 'id': 'Dominance' }, { 'id': "Berserker's Shield" }, { 'id': 'Void Shield' }, { 'id': 'Deathbringer' }, { 'id': 'Talaria Boots' }, { 'id': 'Bristlebush Acorn' }, { 'id': 'Thickbark Acorn' }, { 'id': 'Blackthorn Hammer' }, { 'id': 'Silverbranch Bow' }, { 'id': 'Frostbound Hammer' }, { 'id': "Brawler's Beat Stick" }, { 'id': "Shifter's Shield" }, { 'id': "Gladiator's Shield" }, { 'id': 'Shadowsteel Shuriken' }, { 'id': 'Hastened Katana' }, { 'id': 'Malice' }, { 'id': 'Bloodforge' }, { 'id': 'Thistlethorn Acorn' }, { 'id': 'Runic Shield' }, { 'id': 'The Executioner' }, { 'id': 'Stone Cutting Sword' }, { 'id': 'The Crusher' }, { 'id': 'Rage' }, { 'id': 'Wind Demon' }, { 'id': "Titan's Bane" }, { 'id': 'Transcendence' }, { 'id': 'Serrated Edge' }, { 'id': 'Fail-not' }, { 'id': 'Heartseeker' }, { 'id': 'Warrior Tabi' }, { 'id': 'Golden Blade' }, { 'id': 'Evergreen Acorn' }, { 'id': 'Soul Eater' }, { 'id': "Hydra's Lament" }, { 'id': "Devourer's Gauntlet" }, { 'id': "Jotunn's Wrath" }, { 'id': 'Caduceus Shield' }, { 'id': "Rangda's Mask" }, { 'id': 'Asi' }, { 'id': 'Arondight' }, { 'id': "Qin's Sais" }, { 'id': 'Evolved Transcendence' }, { 'id': "Evolved Devourer's Gauntlet" }, { 'id': 'Evolved Rage' }, { 'id': 'Evolved Soul Eater' },
{'id': 'Lotus Crown'}, {'id': "Jade Emperor's Crown"}, {'id': 'Divine Ruin'}, {'id': "Charon's Coin"}, {'id': 'Obsidian Shard'}, {'id': "Chronos' Pendant"}, {'id': 'Telkhines Ring'}, {'id': "Typhon's Fang"}, {'id': 'Polynomicon'}, {'id': "Bancroft's Talon"}, {'id': "Warlock's Staff"}, {'id': 'Spear of the Magus'}, {'id': 'Book of the Dead'}, {'id': 'Spear of Desolation'}, {'id': 'Gem of Isolation'}, {'id': 'Doom Orb'}, {'id': 'Rod of Tahuti'}, {'id': "Traveler's Shoes"}, {'id': 'Celestial Legion Helm'}, {'id': 'Demonic Grip'}, {'id': "Pythagorem's Piece"}, {'id': 'Book of Thoth'}, {'id': 'Ethereal Staff'}, {'id': 'Hastened Ring'}, {'id': 'Void Stone'}, {'id': 'Soul Gem'}, {'id': 'Stone of Fal'}, {'id': "Rangda's Mask"}, {'id': 'Ring of Hecate'}, {'id': 'Tyrannical Plate Helm'}, {'id': 'Soul Reaver'}, {'id': 'Staff of Myrddin'}, {'id': 'Evolved Book of Thoth'}, {'id': "Evolved Charon's Coin"}, {'id': "Evolved Warlock's Staff"}
]


export const physGods = [
  "Achilles",
  "Ah Muzen Cab",
  "Amaterasu",
  "Anhur",
  "Apollo",
  "Arachne",
  "Artemis",
  "Awilix",
  "Bakasura",
  "Bastet",
  "Bellona",
  "Camazotz",
  "Cernunnos",
  "Chaac",
  "Charybdis",
  "Chernobog",
  "Chiron",
  "Cliodhna",
  "Cu Chulainn",
  "Cupid",
  "Da Ji",
  "Danzaburou",
  "Erlang Shen",
  "Fenrir",
  "Gilgamesh",
  "Guan Yu",
  "Hachiman",
  "Heimdallr",
  "Hercules",
  "Horus",
  "Hou Yi",
  "Hun Batz",
  "Izanami",
  "Jing Wei",
  "Kali",
  "King Arthur",
  "Loki",
  "Medusa",
  "Mercury",
  "Mulan",
  "Ne Zha",
  "Neith",
  "Nemesis",
  "Nike",
  "Odin",
  "Osiris",
  "Pele",
  "Rama",
  "Ratatoskr",
  "Ravana",
  "Serqet",
  "Set",
  "Skadi",
  "Sun Wukong",
  "Susano",
  "Thanatos",
  "Thor",
  "Tsukuyomi",
  "Tyr",
  "Ullr",
  "Vamana",
  "Xbalanque",
];

export const magGods = [
  "Agni",
  "Ah Puch",
  "Anubis",
  "Ao Kuang",
  "Aphrodite",
  "Ares",
  "Artio",
  "Athena",
  "Atlas",
  "Baba Yaga",
  "Bacchus",
  "Baron Samedi",
  "Cabrakan",
  "Cerberus",
  "Chang'e",
  "Chronos",
  "Cthulhu",
  "Discordia",
  "Eset",
  "Fafnir",
  "Freya",
  "Ganesha",
  "Geb",
  "Hades",
  "He Bo",
  "Hel",
  "Hera",
  "Janus",
  "Jormungandr",
  "Khepri",
  "Kukulkan",
  "Kumbhakarna",
  "Kuzenbo",
  "Merlin",
  "Morgan Le Fay",
  "Nox",
  "Nu Wa",
  "Olorun",
  "Persephone",
  "Poseidon",
  "Ra",
  "Raijin",
  "Scylla",
  "Sobek",
  "Sol",
  "Sylvanus",
  "Terra",
  "The Morrigan",
  "Thoth",
  "Tiamat",
  "Vulcan",
  "Xing Tian",
  "Yemoja",
  "Ymir",
  "Zeus",
  "Zhong Kui",
];
