export { default as Godpage } from "./Godpage";
export { default as Navigation } from "./Navigation";
export { default as Home} from "./Home";
export { SinglePostPage as GetPage } from "./GetPage";
export { default as Gods } from "./Gods";
export { default as TierList } from "./Tierlists/TierList";
export { default as CombatTierList } from "./Tierlists/CombatTierList";
export { default as Navbar } from "./Navbar";
export { default as ContactForm } from "./ContactForm"; 
export { default as TierListPage } from "./TierListPage";
export { default as Items } from "./Items";
export { default as Match } from "./Match";